name: dotnet-build-test-deploy

on:
 workflow_dispatch:
 push:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./src                           

    steps:
      - name: Check Out GitHub Code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}
        
      - uses: actions/upload-artifact@v2
        with:
          name: heather-pharma-webapp-pckg
          path: ${{ github.workspace }}
        
  deploy:
    
    needs: [build]

    runs-on: windows-latest
        
    env:
      AZURE_WEBAPP_NAME: test-heather-pharma-webapp    
        
    steps:    
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: actions/download-artifact@v4.1.7
        with:
          name: heather-pharma-webapp-pckg

      - name: 'Run Azure webapp deploy action using service principal'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: ${{ github.workspace }}
